### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by ben8p** [stockmind/dell-xps-9560-ubuntu-respin#10]
Hi, 
This projects looks very interesting. A real life saver!
I looked at the code and I was wondering why many sh files are stored on google drive instead of github ?

That's not handy if someone wants to help...

**Comment by stockmind** [comment]
There is just one bash file on Google Drive and is the isorespin script by http://www.linuxium.com.au/

I don't own any right on that script and is the reason why i've chosen to not include it in the repository directly. Also this let you download the latest version when needed.

You need to ask the author about how to contribute to his code! :)

Everything else is open, free and reusable!
