### ISSUE TITLE
High power consumption with Ubuntu 18.04

### ISSUE THREAD

**Issue by ahmadsocrat** [stockmind/dell-xps-9560-ubuntu-respin#11]
Hi,

When I was with Ubuntu 17.10, the battery used to last longer, powertop reported a discharge rate of around 14 with normal usage on Intel card
Now, after upgrade to 18.04, the discharge rate jumped between 20 and 29, although still on the Intel card

**Comment by stockmind** [comment]
#8 It seems a bug on 18.04 nvidia, is not powered off even if you use the intel card
