### ISSUE TITLE
[Ubuntu 18.04] Error during ISO building on Ubuntu 18.04 - nvidia package missing

### ISSUE THREAD

**Issue by atroy** [stockmind/dell-xps-9560-ubuntu-respin#16]
Hi! I'm trying to build with your provided docker image. First issue was that i have to add a `sleep 5` after the `chmod +x isospin.sh` else i got an error described here https://github.com/moby/moby/issues/9547
It says `/bin/bash: Text file busy`

After if fixed it with the sleep command and a custom image i tried to build with the following command `/docker-respin.sh origin/ubuntu-18.04-desktop-amd64.iso -k v4.17 -c bionicbeaver`. Now I get the the following error `./isorespin.sh: Package 'nvidia-396' not found.`
Am I missing something?

**Comment by stockmind** [comment]
Try to build now with latest commit :)

**Comment by atroy** [comment]
Could you also add a ´sleep 5´ after the chmod? Else everybody with a newer docker version gets `./build.sh: ./isorespin.sh: /bin/bash: bad interpreter: Text file busy` on linux.

**Comment by stockmind** [comment]
Added a sync to force the write as suggested in the issue posted by you

**Comment by atroy** [comment]
Works like a charm! Thanks!
