### ISSUE TITLE
Not applicable to Ubuntu 18.04 beta 2 LTS

### ISSUE THREAD

**Issue by ahmadsocrat** [stockmind/dell-xps-9560-ubuntu-respin#2]
Hi,

First of all, thanks for the great piece of work, you saved my life! Ubuntu 17.10 works with very little issues on my 9560.
However, I can't respin an ISO with Ubuntu 18.04 beta 2 which has been released a few days ago.

I get the error message

~/dell-xps-9560-ubuntu-respin$ ./build.sh ~/Downloads/ubuntu-18.04-beta2-desktop-amd64.iso 

Extracting ISO ...
Parallel unsquashfs: Using 8 processors
140990 inodes (157130 blocks) to write

[=========================================================/] 157130/157130 100%

created 113245 files
created 16948 directories
created 27611 symlinks
created 7 devices
created 0 fifos
Extracting isorespin files ...
Updating bootloader/bootmanager ...
Fetching mainline kernel packages ...
Installing mainline kernel packages ...
Adding repositories ...
Installing packages ...
**./isorespin.sh: Package 'libva1' not found.**

**Comment by stockmind** [comment]
Replace `libva1` with `libva2` in `build.sh` script line 33

This should work!

**Comment by ahmadsocrat** [comment]
Will test it and let you know how it went.

Kind Regards,

Ahmad Amr

**Comment by ahmadsocrat** [comment]
It worked like a charm. ISO was created successfully.

**Comment by stockmind** [comment]
Updated build.sh script to support a new compatibility parameter, new Ubuntu 18.04 could be respinned with "-c bionicbeaver" parameter. 😄
