### ISSUE TITLE
Updating 4.17  kernel to latest version

### ISSUE THREAD

**Issue by huksley** [stockmind/dell-xps-9560-ubuntu-respin#22]
Hello!

Respinned Ubuntu 18.04 on May 4.
I`ve used respin made ISO created by myself. At the time kernel 4.17 was of version 4.17.0-041700rc3
Everything is working well except that the fans are working too much of the time.

How to update kernel now to release version (June 4)? Should I do it?
I notice that apt update/upgrade does not update 4.17 kernel automatically.

**Comment by stockmind** [comment]
Yup, the kernels we are using are far more recent than the official stable version available on apt

If you want to update the kernel to latest version i can suggest you to use UKUU https://github.com/teejee2008/ukuu

**Comment by huksley** [comment]
Is there any specific to XPS 9560 patches applied?

**Comment by stockmind** [comment]
We are using official Canonical builds so, nope, nothing specific for XPS

**Comment by huksley** [comment]
Thanks! Probably should go to main wiki, but still good to have this information here too.

**Comment by stockmind** [comment]
You're right! Done, thanks for feedback! :)
