### ISSUE TITLE
Support of TB16 Docking Station for Dell XPS 9560

### ISSUE THREAD

**Issue by ahmadsocrat** [stockmind/dell-xps-9560-ubuntu-respin#3]
Hi,

I am using the TB16 docking station, and I am facing some compatibility issues in some areas, like for example closing the lid, hot-plugging and unplugging the docking station...etc

Are there any plans to add TB16 support to this image as well?

Kind Regards,

Ahmad Amr

**Comment by stockmind** [comment]
This should be supported by kernel, and it seems that TB16 and TB15 support is not great.

https://www.reddit.com/r/Dell/comments/7juxl8/xps_13_with_tb16_dock_on_linux/
http://vetruvet.blogspot.it/2017/02/linux-on-xps-15-95509560-with-tb16-dock.html

Kernel in ISO is already to 4.15, that is failry new (latest stable is 4.16, you can also try to respin an ISO with that kernel or install an updated mainline kernel with UKUU to test if support is better). It seems that an updated BIOS also may help on fix some issues.
