### ISSUE TITLE
[Ubuntu 18.04] Error: the installed packages do not support PRIME during respin

### ISSUE THREAD

**Issue by hamdanimahdi** [stockmind/dell-xps-9560-ubuntu-respin#4]
Hi,

I tried the command below and got errors related to the Nvidia driver:
`sudo ./build.sh ubuntu-18.04-beta2-desktop-amd64.iso -k v4.15 -c bionicbeaver`

You find attached the logs.
[isorespin.log](https://github.com/stockmind/dell-xps-9560-ubuntu-respin/files/1938725/isorespin.log)

Any idea how  to fix it?
Thank you very much...

**Comment by stockmind** [comment]
ISO has been created successfully, have you tried it? It works?

That error may be a false positive as i'm launching a command inside a chroot that may not have access to any NVIDIA resource, and that command is just to set the Intel as default graphic card for first boot.

**Comment by stockmind** [comment]
Suppressed unnecessary warning as it just misleading.
