### ISSUE TITLE
Q: Install without ISO?

### ISSUE THREAD

**Issue by mariussoutier** [stockmind/dell-xps-9560-ubuntu-respin#40]
Hello there,

Ubuntu/Linux newbie here. I installed Ubuntu 18.04 on my Dell 9560 with success. Can I use your tweaks without setting up an ISO first?

Thanks!

**Comment by stockmind** [comment]
Hi,

Sure you can simply run the
https://github.com/stockmind/dell-xps-9560-ubuntu-respin/blob/master/update.sh script as root.

This will setup your system exactly like a respinned ISO.

**Comment by mariussoutier** [comment]
Cool, thanks :+1:
