### ISSUE TITLE
[Ubuntu 18.04] FDH, Fresh respin install with intell GPU 14-18W discharge rate

### ISSUE THREAD

**Issue by bagobor** [stockmind/dell-xps-9560-ubuntu-respin#46]
Hi!
1. Thank you for this impressive work!
2. I did all the steps of your instruction but got higher power drain (FHD model, 32GB RAM)

Any ideas to try to improve battery life? 
Thank you!

**Comment by stockmind** [comment]
Hi! 

Try to clone this repository and run `update.sh -c bionicbeaver` script

Reboot and check your `GRUB_CMDLINE_LINUX_DEFAULT`, `GRUB_CMDLINE_LINUX` lines and the status of the gpuoff service

```
grep /etc/default/grub "GRUB_CMDLINE_LINUX"
sudo systemctl status gpuoff
```

Issue #8 may help you

Let me know

**Comment by bagobor** [comment]
@stockmind  thank you! I'll do it now. (btw after switching to windows and back it's ~22-23w ... ) 
with only one terminal opened after fresh reboot.

**Comment by bagobor** [comment]
straight after update.sh/reboot I have ~12-15w - COOL!

**Comment by bagobor** [comment]
Grub kernel params were update to:
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash acpi_rev_override=1"
GRUB_CMDLINE_LINUX="quiet splash acpi_rev_override=1"

**Comment by bagobor** [comment]
"cat /sys/bus/pci/devices/0000\:01\:00.0/power/control" gives me 'auto'

**Comment by bagobor** [comment]
So:
I managed to get 9.2W without wifi/bt + min screen brightness and lowest CPU mode with any apps running except terminal with powertop with GRUB_CMDLINE_LINUX_DEFAULT="quiet splash i915.modeset=1 nouveau.modeset=0"

**Comment by bagobor** [comment]
So the lowest power drain I've managed to get so far:
9.2W
for
CPU: Intel Core i7-7700HQ 32GB of RAM, 1TB WD Black 2nd gen with FHD screen

@stockmind do you think it's possible to optimize it some more? 
thank you!

**Comment by bagobor** [comment]
@stockmind the weird thing is that I need to set mode to nvidia and then to intel (without reboot) reduce power consumption. Any advice on how to automate it? Thank . you!
