### ISSUE TITLE
9560 with 18.10 or 18.10 respin successes?

### ISSUE THREAD

**Issue by jeffreyscottgraham** [stockmind/dell-xps-9560-ubuntu-respin#53]
Has anyone tried stock 18.10 or an 18.10 respin with the 9560?

**Comment by boxcee** [comment]
Here it seems: https://github.com/stockmind/dell-xps-9560-ubuntu-respin/issues/52#issuecomment-470489630

**Comment by stockmind** [comment]
Just updated the build scripts, i'm building some ISO and will upload them!
