### ISSUE TITLE
Error: "isorespin.sh: Access to the internet is required for downloading files"

### ISSUE THREAD

**Issue by serpro69** [stockmind/dell-xps-9560-ubuntu-respin#55]
Getting `isorespin.sh: Access to the internet is required for downloading files`.

Commented out the `CLEAN_EXIT` inside the function, got above error messages, but the respin seemed to work fine afterwards (at least finished without errors). Still would like to figure out the issue here. Any thoughts?

**Comment by stockmind** [comment]
Are you behind a proxy, VPN or have a restricted internet access?

**Comment by serpro69** [comment]
Yes, you're right, it's my connection... I didn't check it thoroughly because I tried from couple of wifi networks and had the same error, so I dismissed the idea. Now that you mentioned it I tried to connect to a mobile network from my phone and it worked fine. Thanks!
