### ISSUE TITLE
Ubuntu 18.04 Issue

### ISSUE THREAD

**Issue by knpk13** [stockmind/dell-xps-9560-ubuntu-respin#7]
Hello,

I am trying to get started with linux on my new laptop as I am studying computer science. I am having trouble installing Ubuntu 18.04 on this particular laptop, just like I had trouble installing and using previous versions of ubuntu on it, which is preventing me from making linux my primary OS. I followed the required steps from (https://github.com/rcasero/doc/wiki/Ubuntu-linux-on-Dell-XPS-15-(9560)) and can "sometimes" boot into the live USB (not always). And I didnt have to set nouveau.modeset=0. When I am able to boot into it, I follow the install instructions till the last prompt, after which the installer simply force closes. Rebooting/shutdown instantly freezes the entire machine. I would like some help installing 18.04 and I hope this guide is updated for it. I am willing to provide logs but I am not sure which ones to provide and how to obtain them. Thank you in advance.

**Comment by stockmind** [comment]
Respin the Ubuntu 18.04 iso following the README steps carefully and burn the iso builded on a USB with Etcher.
Be sure to disable secure boot in bios. Then boot and install normally.

We are facing some issues on shutdown when intel graphic is selected as default graphic card.
I'm waiting to find a fix for this, then i will update a ready to use iso.

If you want to use a ready to use iso you can find Ubuntu 17.10 here https://github.com/stockmind/dell-xps-9560-ubuntu-respin/releases

That iso is perfectly stable and works out of the box.

**Comment by stockmind** [comment]
Exprimental 18.04 iso provided here: https://downloads.cre.ovh/
No guarantee it works good.

**Comment by rvanginneken** [comment]
Is the shutdown problem still an issue? There's nothing about it in the README
