### ISSUE TITLE
Release ISO (17.10) throws 403 Server Error

### ISSUE THREAD

**Issue by heroheman** [stockmind/dell-xps-9560-ubuntu-respin#9]
Just a headsup, I am trying to downgrade right now from 18.04 to 17.10 (Its not usable right now with an nvidia card) and this project seemed fine. But I cant download the Iso. After the download starts, I can download 10-15% of the image and then the server changes to 403.

**Comment by stockmind** [comment]
ISO is hosted on github servers so it may be a temporary issue on their
side. there is no much i can do about it. I will try to provide a mirror as
soon as possible. Anyway you can download a normal 17.10 ubuntu ISO and
respin it yourself in a virtual machine or using Docker!

Il ven 4 mag 2018, 10:21 Florenz Heldermann <notifications@github.com> ha
scritto:

**Comment by heroheman** [comment]
thx for the reply, will do that.
Note: Had the 403 yesterday and today on two different devices and several browsers. Maybe not temporary.

**Comment by stockmind** [comment]
Just downloaded now without issues, are sure your network is stable?

**Comment by stockmind** [comment]
Anyway i have setup a space right now and i'm uploading the stable 17.10 and 18.04 (experimental) iso there :)
You will find everything here in half an hour approximately :)

https://downloads.cre.ovh/

**Comment by stockmind** [comment]
ISO online, try from this mirror and let me know!

https://downloads.cre.ovh/
